[build]
  base = "mock-interview/"
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://mock-interview-backend.railway.app/api"
  VITE_SOCKET_URL = "https://mock-interview-backend.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://mock-interview-backend.railway.app/api"
  VITE_SOCKET_URL = "https://mock-interview-backend.railway.app"
