[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cp backend/package*.json .", "npm ci --prefix backend"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend && node index.js"
