[build]
  base = "."
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://meetly-chat.vercel.app/api"
  VITE_SOCKET_URL = "https://meetly-chat.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
