[build]
  base = "."
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://meetlychat.onrender.com/api"
  VITE_SOCKET_URL = "https://meetlychat.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://meetlychat.onrender.com/api"
  VITE_SOCKET_URL = "https://meetlychat.onrender.com"
